######################################################################
# Automatically generated by qmake (3.0) Sa. Mär. 29 15:38:00 2014
######################################################################

TEMPLATE = app
TARGET = ts
INCLUDEPATH += . ./lib

# Input
FORMS += ui/main.ui
TRANSLATIONS += lang/de.ts lang/en.ts
