# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Tue Apr  1 21:25:42 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1057, 766)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("logo.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.mainTab = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainTab.sizePolicy().hasHeightForWidth())
        self.mainTab.setSizePolicy(sizePolicy)
        self.mainTab.setObjectName(_fromUtf8("mainTab"))
        self.tab_9 = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_9.sizePolicy().hasHeightForWidth())
        self.tab_9.setSizePolicy(sizePolicy)
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_9)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.toxTryDeleteFriend = QtGui.QPushButton(self.tab_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toxTryDeleteFriend.sizePolicy().hasHeightForWidth())
        self.toxTryDeleteFriend.setSizePolicy(sizePolicy)
        self.toxTryDeleteFriend.setObjectName(_fromUtf8("toxTryDeleteFriend"))
        self.gridLayout.addWidget(self.toxTryDeleteFriend, 3, 1, 1, 1)
        self.label_44 = QtGui.QLabel(self.tab_9)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout.addWidget(self.label_44, 1, 0, 1, 1)
        self.toxTryFriends = QtGui.QListWidget(self.tab_9)
        self.toxTryFriends.setObjectName(_fromUtf8("toxTryFriends"))
        self.gridLayout.addWidget(self.toxTryFriends, 2, 0, 1, 2)
        self.toxTryFriendInfos = QtGui.QTextEdit(self.tab_9)
        self.toxTryFriendInfos.setDocumentTitle(_fromUtf8(""))
        self.toxTryFriendInfos.setUndoRedoEnabled(False)
        self.toxTryFriendInfos.setReadOnly(True)
        self.toxTryFriendInfos.setObjectName(_fromUtf8("toxTryFriendInfos"))
        self.gridLayout.addWidget(self.toxTryFriendInfos, 5, 0, 1, 2)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_25 = QtGui.QLabel(self.tab_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_5.addWidget(self.label_25, 3, 0, 1, 1)
        self.label_42 = QtGui.QLabel(self.tab_9)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_5.addWidget(self.label_42, 0, 0, 1, 1)
        self.label_43 = QtGui.QLabel(self.tab_9)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_5.addWidget(self.label_43, 4, 0, 1, 1)
        self.toxTryUsername = QtGui.QLineEdit(self.tab_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toxTryUsername.sizePolicy().hasHeightForWidth())
        self.toxTryUsername.setSizePolicy(sizePolicy)
        self.toxTryUsername.setObjectName(_fromUtf8("toxTryUsername"))
        self.gridLayout_5.addWidget(self.toxTryUsername, 0, 2, 1, 1)
        self.toxTryStatus = QtGui.QComboBox(self.tab_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toxTryStatus.sizePolicy().hasHeightForWidth())
        self.toxTryStatus.setSizePolicy(sizePolicy)
        self.toxTryStatus.setObjectName(_fromUtf8("toxTryStatus"))
        self.toxTryStatus.addItem(_fromUtf8(""))
        self.toxTryStatus.addItem(_fromUtf8(""))
        self.toxTryStatus.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.toxTryStatus, 4, 2, 1, 1)
        self.label_46 = QtGui.QLabel(self.tab_9)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_5.addWidget(self.label_46, 5, 0, 1, 1)
        self.toxTryStatusMessage = QtGui.QLineEdit(self.tab_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toxTryStatusMessage.sizePolicy().hasHeightForWidth())
        self.toxTryStatusMessage.setSizePolicy(sizePolicy)
        self.toxTryStatusMessage.setObjectName(_fromUtf8("toxTryStatusMessage"))
        self.gridLayout_5.addWidget(self.toxTryStatusMessage, 5, 2, 1, 1)
        self.toxTryId = QtGui.QLineEdit(self.tab_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toxTryId.sizePolicy().hasHeightForWidth())
        self.toxTryId.setSizePolicy(sizePolicy)
        self.toxTryId.setObjectName(_fromUtf8("toxTryId"))
        self.gridLayout_5.addWidget(self.toxTryId, 3, 1, 1, 2)
        self.gridLayout.addLayout(self.gridLayout_5, 0, 0, 1, 2)
        self.label_47 = QtGui.QLabel(self.tab_9)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout.addWidget(self.label_47, 6, 0, 1, 1)
        self.toxTryNewFriendRequest = QtGui.QPushButton(self.tab_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toxTryNewFriendRequest.sizePolicy().hasHeightForWidth())
        self.toxTryNewFriendRequest.setSizePolicy(sizePolicy)
        self.toxTryNewFriendRequest.setObjectName(_fromUtf8("toxTryNewFriendRequest"))
        self.gridLayout.addWidget(self.toxTryNewFriendRequest, 3, 0, 1, 1)
        self.label_45 = QtGui.QLabel(self.tab_9)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout.addWidget(self.label_45, 4, 0, 1, 1)
        self.toxTryNotifications = QtGui.QTextEdit(self.tab_9)
        self.toxTryNotifications.setDocumentTitle(_fromUtf8(""))
        self.toxTryNotifications.setUndoRedoEnabled(False)
        self.toxTryNotifications.setReadOnly(True)
        self.toxTryNotifications.setObjectName(_fromUtf8("toxTryNotifications"))
        self.gridLayout.addWidget(self.toxTryNotifications, 7, 0, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.toxTrySendText = QtGui.QLineEdit(self.tab_9)
        self.toxTrySendText.setObjectName(_fromUtf8("toxTrySendText"))
        self.gridLayout_2.addWidget(self.toxTrySendText, 1, 0, 1, 1)
        self.toxTrySendButton = QtGui.QPushButton(self.tab_9)
        self.toxTrySendButton.setObjectName(_fromUtf8("toxTrySendButton"))
        self.gridLayout_2.addWidget(self.toxTrySendButton, 1, 1, 1, 1)
        self.toxTryChat = QtGui.QTextEdit(self.tab_9)
        self.toxTryChat.setFrameShape(QtGui.QFrame.StyledPanel)
        self.toxTryChat.setFrameShadow(QtGui.QFrame.Sunken)
        self.toxTryChat.setReadOnly(True)
        self.toxTryChat.setObjectName(_fromUtf8("toxTryChat"))
        self.gridLayout_2.addWidget(self.toxTryChat, 0, 0, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_7.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.mainTab.addTab(self.tab_9, icon, _fromUtf8(""))
        self.settings = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings.sizePolicy().hasHeightForWidth())
        self.settings.setSizePolicy(sizePolicy)
        self.settings.setObjectName(_fromUtf8("settings"))
        self.gridLayout_6 = QtGui.QGridLayout(self.settings)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.formLayout_7 = QtGui.QFormLayout()
        self.formLayout_7.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.formLayout_7.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_7.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.label_23 = QtGui.QLabel(self.settings)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_23)
        self.configList = QtGui.QListWidget(self.settings)
        self.configList.setObjectName(_fromUtf8("configList"))
        self.formLayout_7.setWidget(3, QtGui.QFormLayout.SpanningRole, self.configList)
        self.label_26 = QtGui.QLabel(self.settings)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.formLayout_7.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_26)
        self.configKey = QtGui.QLineEdit(self.settings)
        self.configKey.setObjectName(_fromUtf8("configKey"))
        self.formLayout_7.setWidget(4, QtGui.QFormLayout.FieldRole, self.configKey)
        self.label_27 = QtGui.QLabel(self.settings)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.formLayout_7.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_27)
        self.configValue = QtGui.QLineEdit(self.settings)
        self.configValue.setObjectName(_fromUtf8("configValue"))
        self.formLayout_7.setWidget(5, QtGui.QFormLayout.FieldRole, self.configValue)
        self.createConfig = QtGui.QPushButton(self.settings)
        self.createConfig.setObjectName(_fromUtf8("createConfig"))
        self.formLayout_7.setWidget(6, QtGui.QFormLayout.LabelRole, self.createConfig)
        self.saveConfig = QtGui.QPushButton(self.settings)
        self.saveConfig.setObjectName(_fromUtf8("saveConfig"))
        self.formLayout_7.setWidget(6, QtGui.QFormLayout.FieldRole, self.saveConfig)
        self.deleteConfig = QtGui.QPushButton(self.settings)
        self.deleteConfig.setObjectName(_fromUtf8("deleteConfig"))
        self.formLayout_7.setWidget(7, QtGui.QFormLayout.FieldRole, self.deleteConfig)
        self.horizontalLayout_2.addLayout(self.formLayout_7)
        self.textEdit = QtGui.QTextEdit(self.settings)
        self.textEdit.setUndoRedoEnabled(False)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.horizontalLayout_2.addWidget(self.textEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.mainTab.addTab(self.settings, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.mainTab, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1057, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.mainTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "tryTox", None))
        self.toxTryDeleteFriend.setText(_translate("MainWindow", "Delete friend", None))
        self.label_44.setText(_translate("MainWindow", "Friendlist", None))
        self.label_25.setText(_translate("MainWindow", "Your ID", None))
        self.label_42.setText(_translate("MainWindow", "Username", None))
        self.label_43.setText(_translate("MainWindow", "Status", None))
        self.toxTryStatus.setItemText(0, _translate("MainWindow", "Online", None))
        self.toxTryStatus.setItemText(1, _translate("MainWindow", "Away", None))
        self.toxTryStatus.setItemText(2, _translate("MainWindow", "Busy", None))
        self.label_46.setText(_translate("MainWindow", "Statusmessage", None))
        self.toxTryStatusMessage.setText(_translate("MainWindow", "I\'m alive!", None))
        self.label_47.setText(_translate("MainWindow", "Notifications", None))
        self.toxTryNewFriendRequest.setText(_translate("MainWindow", "Add new Friend", None))
        self.label_45.setText(_translate("MainWindow", "FriendInfos", None))
        self.toxTryNotifications.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans Serif\';\"><br /></p></body></html>", None))
        self.toxTrySendButton.setText(_translate("MainWindow", "Send", None))
        self.mainTab.setTabText(self.mainTab.indexOf(self.tab_9), _translate("MainWindow", "ToxTry", None))
        self.label_23.setText(_translate("MainWindow", "Configs", None))
        self.label_26.setText(_translate("MainWindow", "Key", None))
        self.label_27.setText(_translate("MainWindow", "Value", None))
        self.createConfig.setText(_translate("MainWindow", "Create", None))
        self.saveConfig.setText(_translate("MainWindow", "Save", None))
        self.deleteConfig.setText(_translate("MainWindow", "Delete", None))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:18pt; text-decoration: underline;\">Avaible Config-Keys</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\';\">* lang / language = language - put the right filename (*.qm in your folder) there</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\';\">* encrypted : 1=CAST, 2=Blowfish, 3=DES3,4=ARC4,5=XOR,6=AES,7=ARC2 (you need to install pycrypto / python3-crypto @ *buntu). Put &quot;None&quot; as value for going back to cleartext. Encryption shouldn\'t need any restart.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\';\">* consoleHandlerLogLevel / fileHandlerLogLevel accept the following values:        fatal, error, warning, info and debug. Default is error (also used if you do typo). Shouldn\'t need restart.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\';\">Restart is needed after changes!</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans Serif\';\"><br /></p></body></html>", None))
        self.mainTab.setTabText(self.mainTab.indexOf(self.settings), _translate("MainWindow", "Settings", None))

